# -*- coding: utf-8 -*-
"""Day 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nu1JMtVQNBtDt1cJddvkVGAgIxjIsJQq

ControlFlow --Day 3
"""

print("Welcome to the rollercoaster!")
height = int(input("What is your height in cm? "))
if height >= 120:
  print ("You can ride the rollercoaster !! ")
  age = int(input("What is you age? "))
  if age < 12:
    print("Please pay $5")
  elif age <= 18 :
    print("Please pay $7")
  else:
    print ("The ticket price would be 12$")
else :
  print ("Sorry, you have to grow taller befoer you ride ")

number = int(input("Which number do you want to check ?"))

remainder = number%2  # Modulo Operator  -- Gives remainders

if remainder == 0:
  print("The given number is an Even Number")
else:
  print("The given number is an Odd number")

height = float(input("Enter your height in m: "))
weight = float(input("Enter your weight in kgs: "))

BMI = round(weight/ (height*height))
print (BMI)

if BMI < 18.5 :
  print(f"Your bmi is {BMI}, You are underweight")
elif BMI < 25 :
  print(f"Your bmi is {BMI}, You have a normal weight")
elif BMI < 30 :
  print(f"Your bmi is {BMI}, You are overweight")
elif BMI < 35 :
  print (f"Your bmi is {BMI}, You are obese")
else :
  print (f"Your bmi is {BMI}, you are clinically obese")

"""For the Leap year excercise done below, it is always recommended to draw a flowchart so as to understand the logic."""

year = int(input("Which year do you want to check "))

if year%4 == 0 :
  if year%100 == 0 :
    if year%400 == 0:
      print ("The year is a leap year")
    else :
      print ("Not a Leap Year")
  else :
    print ("It is a leap Year")
else :
  print ("The given year is not a leap year")

"""A small addition to the above code."""

print("Welcome to the rollercoaster!")
height = int(input("What is your height in cm? "))
bill = 0
if height >= 120:
  print ("You can ride the rollercoaster !! ")
  age = int(input("What is you age? "))
  if age < 12:
    bill = 5
    print("Child Ticket are $5")
  elif age <= 18 :
    bill = 7
    print("Teenage Ticket are $7")
  else:
    bill = 12
    print ("Adult tickets are 12$")
  wants_pic = input("Do you want a photo taken ? Type Y for yes and N for no -- ")
  if wants_pic == "Y" :
    bill = bill + 3

  print (f"The final Bill is:-  ${bill}")
else :
  print ("Sorry, you have to grow taller befoer you ride ")